version: 1.0.{build}

branches:
  only:
    - enable-ci-windows

image: Visual Studio 2017

environment:
  nodejs_version: "6.11.3"
  PYTHON: "C:\\Python36-x64"
  matrix:
    - VSVER: 14

clone_folder: c:\proj\rclnodejs

platform:
  - x64

before_build:
  - cmd: |
         cd c:\
         md download
         cd download
         appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2017-04-04-1/asio.1.10.6.nupkg
         appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2017-04-04-1/eigen.3.3.3.nupkg
         appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2017-04-04-1/tinyxml-usestl.2.6.2.nupkg
         appveyor DownloadFile https://github.com/ros2/choco-packages/releases/download/2017-04-04-1/tinyxml2.4.0.1.nupkg
         choco install -y -s c:\download\ asio eigen tinyxml-usestl tinyxml2
         appveyor DownloadFile http://ci.ros2.org/view/packaging/job/packaging_windows/lastSuccessfulBuild/artifact/ws/ros2-package-windows-AMD64.zip
         7z x -y "c:\download\ros2-package-windows-AMD64.zip" -o"c:\opencv" > nul
  - "SET PATH=%PYTHON%;%PYTHON%\\bin;%PYTHON%\\Scripts;%PATH%"
  # Show version and architecture for Python
  - "%PYTHON%\\python.exe --version"
  - cmd: pip install -U setuptools pip

build_script:
  - git submodule update --init --recursive
  - cmd: call c:\ros2-windows\local_setup.bat
  - set PYTHON=C:\Python27-x64
  - npm install

test: off
